package com.pokewords.constants;

public enum  SpriteTypes {
    ROOT,  // the root of all types

    MENU,
    MENU_PLAY_BUTTON,
    MENU_MULTIPLAYER_BUTTON,

    CHARACTER,
    HERO,
    MONSTER,

    BALL, SNOW_BALL, SNOW_BALL_EX, EVIL, BLACK_GUNNER, BLACK_BOSS, RIFLE_TANK, SNIPPER_TANK, CRAZY_CAT,

    PICKABLE,
    PICKABLE_ITEM,
    PICKABLE_GUN,
    PICKABLE_PISTOL,
    PICKABLE_MACHINE_GUN,
    PICKABLE_SNIPER_RIFLE,

    BULLET,
    BULLET_BLUE_PELLET,
    BULLET_FIRE_RIFLE;
}
